version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pack_service
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - PORT=3000
    networks:
      - pack_network
    restart: unless-stopped


networks:
  default:
    driver: bridge
  pack_network:
    driver: bridge
